export const VIDEOS_ACTION_TYPES = {
  FETCH_MAIN_VIDEOS_START: 'FETCH_MAIN_VIDEOS_START',
  FETCH_MAIN_VIDEOS_SUCCESS: 'FETCH_MAIN_VIDEOS_SUCCESS',
  FETCH_MAIN_VIDEOS_FAILED: 'FETCH_MAIN_VIDEOS_FAILED:',
  SET_IS_LOADING_MAIN_VIDEOS: 'SET_IS_LOADING_MAIN_VIDEOS',
  FETCH_CATEGORY_VIDEOS_START: 'FETCH_CATEGORY_VIDEOS_START',
  FETCH_CATEGORY_VIDEOS_SUCCESS: 'FETCH_CATEGORY_VIDEOS_SUCCESS',
  FETCH_CATEGORY_VIDEOS_FAILED: 'FETCH_CATEGORY_VIDEOS_FAILED:',
  SET_IS_LOADING_CATEGORY_VIDEOS: 'SET_IS_LOADING_CATEGORY_VIDEOS',
  SET_VIDEOS_IN_USE: 'SET_VIDEOS_IN_USE',
}
