export const PHOTOS_ACTION_TYPES = {
  FETCH_MAIN_PHOTOS_START: 'FETCH_MAIN_PHOTOS_START',
  FETCH_MAIN_PHOTOS_SUCCESS: 'FETCH_MAIN_PHOTOS_SUCCESS',
  FETCH_MAIN_PHOTOS_FAILED: 'FETCH_MAIN_PHOTOS_FAILED',
  SET_IS_LOADING_MAIN_PHOTOS: 'SET_IS_LOADING_MAIN_PHOTOS',
  FETCH_CATEGORY_PHOTOS_START: 'FETCH_CATEGORY_PHOTOS_START',
  FETCH_CATEGORY_PHOTOS_SUCCESS: 'FETCH_CATEGORY_PHOTOS_SUCCESS',
  FETCH_CATEGORY_PHOTOS_FAILED: 'FETCH_CATEGORY_PHOTOS_FAILED',
  SET_IS_LOADING_CATEGORY_PHOTOS: 'SET_IS_LOADING_CATEGORY_PHOTOS',
  CATEGORY_SELECTED: 'CATEGORY_SELECTED',
}
