import "./globals.css";
import Navigation from '../components/Navigation';



export const metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
            <Navigation/>
            {children}
            <footer className="py-16">
                <p className="text-center">&copy; 2024 My Portfolio</p>
            </footer>
        </body>
    </html>
  );
}
