
import "./globals.css";
import Navigation from '../components/navigation/Navigation';
import Providers from "@/utils/providers";



export const metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
};


export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body>
        <Providers>
            <Navigation/>
            <div className="bg-background-gradient text-gray-200 font-roboto flex flex-col w-full h-screen">
                <main>
                    <section>
                        {children}
                    </section>
                </main>
            </div>
            <footer className="py-16 bg-bottom-grad">
                <p className="text-center text-secondary-text">&copy; 2024 My Portfolio</p>
            </footer>
        </Providers>
        </body>
        </html>
);
}
