
import "./globals.css";
import Navigation from '../components/Navigation';
import Providers from "@/utils/providers";



export const metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
};


export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body>
        <Providers>
                <Navigation />
                {children}
                <footer className="py-16 bg-bottom-grad">
                    <p className="text-center text-secondary-text">&copy; 2024 My Portfolio</p>
                </footer>
        </Providers>
        </body>
        </html>
    );
}
